extends Node

const PIECES_PER_SIDE = 7

var show_tooltips : bool = true

enum PLAYER { ONE, TWO }
enum PLAYER_2_TYPE {
	HUMAN, AI, NETWORK
}

enum COLORS {
	BLACK, WHITE, TILE
}

enum DIFFICULTY {
	EASY,
	NORMAL,
	HARD
}

enum PIECE_BASE {
	PAWN,
	BISHOP,
	ROOK,
	KNIGHT,
	KING,
	QUEEN
}

enum BORDER_STYLE {
	BOX,
	CIRCLE,
	TARGET,
	HIGHLIGHT,
	FRIENDLY
}

#pieces
enum PIECE_TYPES {
	#KNIGHT,
	#BISHOP,
	#KING,
	PAWN,
	HORSE_ARCHER,
	ARCHBISHOP,
	MITOSIS_PAWN,
	SHIELD_KING,
	DUCK,
	WORM,
	CHECKER,
	EXPLODING_BISHOP,
	ACROBISHOP,
	JOUST_BISHOP,
	STUN_KNIGHT,
	TROJAN_HORSE,
	GUARDIAN_ANGEL,
	SUMO,
	MAGMA_KNIGHT,
	DUPLICATOR,
	WARHORSE,
	INFECTOR, #21
	JUGGERNAUT,
	JUGGERNAUT2,
	JUGGERNAUT1,
	WIZARD,
	WATER,
	#BRIDGE_LEFT,
	#BRIDGE_MID,
	#BRIDGE_RIGHT,
	#BRIDGE_FULL,
	WEB,
	MAGMA_HIGH,
	MAGMA_MED,
	MAGMA_LOW,
	BRICKS,
	TREE
}


const SPRITE_MAPPING = {
	COLORS.BLACK : {
		#PIECE_TYPES.KING: Vector2i(0, 0),
		PIECE_TYPES.PAWN: Vector2i(0, 1),
		#PIECE_TYPES.BISHOP: Vector2i(0, 2),
		#PIECE_TYPES.KNIGHT: Vector2i(0, 3),
		PIECE_TYPES.SHIELD_KING: Vector2i(0, 4),
		PIECE_TYPES.DUCK: Vector2i(0, 5),
		PIECE_TYPES.MITOSIS_PAWN: Vector2i(0, 6),
		PIECE_TYPES.WORM: Vector2i(0, 7),
		PIECE_TYPES.CHECKER: Vector2i(0, 8),
		PIECE_TYPES.EXPLODING_BISHOP: Vector2i(0, 9),
		PIECE_TYPES.ACROBISHOP: Vector2i(0, 10),
		PIECE_TYPES.ARCHBISHOP: Vector2i(0, 11),
		PIECE_TYPES.JOUST_BISHOP: Vector2i(0, 12),
		PIECE_TYPES.STUN_KNIGHT: Vector2i(0, 13),
		PIECE_TYPES.HORSE_ARCHER: Vector2i(0, 14),
		PIECE_TYPES.TROJAN_HORSE: Vector2i(0, 15),
		PIECE_TYPES.GUARDIAN_ANGEL: Vector2i(0,16),
		PIECE_TYPES.SUMO: Vector2i(0,17),
		PIECE_TYPES.MAGMA_KNIGHT: Vector2i(0,18),
		PIECE_TYPES.DUPLICATOR: Vector2i(0,19),
		PIECE_TYPES.WARHORSE: Vector2i(0, 20),
		PIECE_TYPES.INFECTOR: Vector2i(0, 21),
		PIECE_TYPES.JUGGERNAUT: Vector2i(0, 22),
		PIECE_TYPES.JUGGERNAUT2: Vector2i(0, 23),
		PIECE_TYPES.JUGGERNAUT1: Vector2i(0, 24),
		PIECE_TYPES.WIZARD: Vector2i(0, 25)
	},
	COLORS.WHITE:{
		#PIECE_TYPES.KING: Vector2i(1, 0),
		PIECE_TYPES.PAWN: Vector2i(1, 1),
		#PIECE_TYPES.BISHOP: Vector2i(1, 2),
		#PIECE_TYPES.KNIGHT: Vector2i(1, 3),
		PIECE_TYPES.SHIELD_KING: Vector2i(1, 4),
		PIECE_TYPES.DUCK: Vector2i(1, 5),
		PIECE_TYPES.MITOSIS_PAWN: Vector2i(1, 6),
		PIECE_TYPES.WORM: Vector2i(1, 7),
		PIECE_TYPES.CHECKER: Vector2i(1, 8),
		PIECE_TYPES.EXPLODING_BISHOP: Vector2i(1, 9),
		PIECE_TYPES.ACROBISHOP: Vector2i(1, 10),
		PIECE_TYPES.ARCHBISHOP: Vector2i(1, 11),
		PIECE_TYPES.JOUST_BISHOP: Vector2i(1, 12),
		PIECE_TYPES.STUN_KNIGHT: Vector2i(1, 13),
		PIECE_TYPES.HORSE_ARCHER: Vector2i(1, 14),
		PIECE_TYPES.TROJAN_HORSE: Vector2i(1, 15),
		PIECE_TYPES.GUARDIAN_ANGEL: Vector2i(1,16),
		PIECE_TYPES.SUMO: Vector2i(1,17),
		PIECE_TYPES.MAGMA_KNIGHT: Vector2i(1,18),
		PIECE_TYPES.DUPLICATOR: Vector2i(1,19),
		PIECE_TYPES.WARHORSE: Vector2i(1, 20),
		PIECE_TYPES.INFECTOR: Vector2i(1, 21),
		PIECE_TYPES.JUGGERNAUT: Vector2i(1, 22),
		PIECE_TYPES.JUGGERNAUT2: Vector2i(1, 23),
		PIECE_TYPES.JUGGERNAUT1: Vector2i(1, 24),
		PIECE_TYPES.WIZARD: Vector2i(1, 25)
	},
	COLORS.TILE:{
		PIECE_TYPES.WATER: Vector2i(2,0),
		#PIECE_TYPES.BRIDGE_LEFT: Vector2i(2,1),
		#PIECE_TYPES.BRIDGE_MID: Vector2i(2,2),
		#PIECE_TYPES.BRIDGE_RIGHT: Vector2i(2,3),
		#PIECE_TYPES.BRIDGE_FULL: Vector2i(2,4),
		PIECE_TYPES.WEB: Vector2i(2,5),
		PIECE_TYPES.MAGMA_HIGH: Vector2i(2,6),
		PIECE_TYPES.MAGMA_MED: Vector2i(2,7),
		PIECE_TYPES.MAGMA_LOW: Vector2i(2,8),
		PIECE_TYPES.BRICKS: Vector2i(2,9),
		PIECE_TYPES.TREE: Vector2i(2,10),
	}
}

const INITIAL_PIECE_SET_SINGLE = [
	#[PIECE_TYPES.ARCHBISHOP, 0, 0],
	#[PIECE_TYPES.HORSE_ARCHER, 1, 0],
	#[PIECE_TYPES.MITOSIS_PAWN, 2, 0],
	#[PIECE_TYPES.QUEEN, 3, 0],
	#[PIECE_TYPES.KING, 4, 0],
	#[PIECE_TYPES.BISHOP, 5, 0]
]
