extends Node

enum PLAYER { ONE, TWO }
enum PLAYER_2_TYPE {
	HUMAN, AI
}

enum COLORS {
	BLACK, WHITE
}

enum PIECE_TYPES {
	ROOK,
	KNIGHT,
	BISHOP,
	QUEEN,
	KING,
	PAWN,
	HORSE_ARCHER,
	ARCHBISHOP,
	MITOSIS_PAWN,
	SHIELD_KING,
	DUCK,
	WORM,
	CHECKER,
	EXPLODING_BISHOP,
	ACROBISHOP,
	JOUSTING_BISHOP,
	STUN_KNIGHT,
	TROJAN_HORSE
}

const SPRITE_MAPPING = {
	COLORS.BLACK : {
		PIECE_TYPES.ROOK: Vector2i(0, 4),
		PIECE_TYPES.KNIGHT: Vector2i(0, 3),
		PIECE_TYPES.BISHOP: Vector2i(0, 2),
		PIECE_TYPES.QUEEN: Vector2i(0, 4),
		PIECE_TYPES.KING: Vector2i(0, 0),
		PIECE_TYPES.PAWN: Vector2i(0, 1),
		PIECE_TYPES.HORSE_ARCHER: Vector2i(0, 14),
		PIECE_TYPES.ARCHBISHOP: Vector2i(0, 11),
		PIECE_TYPES.MITOSIS_PAWN: Vector2i(0, 6),
		PIECE_TYPES.SHIELD_KING: Vector2i(0, 4),
		PIECE_TYPES.DUCK: Vector2i(0, 5),
		PIECE_TYPES.WORM: Vector2i(0, 7),
		PIECE_TYPES.CHECKER: Vector2i(0, 8),
		PIECE_TYPES.EXPLODING_BISHOP: Vector2i(0, 9),
		PIECE_TYPES.ACROBISHOP: Vector2i(0, 10),
		PIECE_TYPES.JOUSTING_BISHOP: Vector2i(0, 12),
		PIECE_TYPES.STUN_KNIGHT: Vector2i(0, 13),
		PIECE_TYPES.TROJAN_HORSE: Vector2i(0, 15)
	},
	COLORS.WHITE:{
		PIECE_TYPES.ROOK: Vector2i(1, 4),
		PIECE_TYPES.KNIGHT: Vector2i(1, 3),
		PIECE_TYPES.BISHOP: Vector2i(1, 2),
		PIECE_TYPES.QUEEN: Vector2i(1, 4),
		PIECE_TYPES.KING: Vector2i(1, 0),
		PIECE_TYPES.PAWN: Vector2i(1, 1),
		PIECE_TYPES.HORSE_ARCHER: Vector2i(1, 14),
		PIECE_TYPES.ARCHBISHOP: Vector2i(1, 11),
		PIECE_TYPES.MITOSIS_PAWN: Vector2i(1, 6),
		PIECE_TYPES.SHIELD_KING: Vector2i(1, 4),
		PIECE_TYPES.DUCK: Vector2i(1, 5),
		PIECE_TYPES.WORM: Vector2i(1, 7),
		PIECE_TYPES.CHECKER: Vector2i(1, 8),
		PIECE_TYPES.EXPLODING_BISHOP: Vector2i(1, 9),
		PIECE_TYPES.ACROBISHOP: Vector2i(1, 10),
		PIECE_TYPES.JOUSTING_BISHOP: Vector2i(1, 12),
		PIECE_TYPES.STUN_KNIGHT: Vector2i(1, 13),
		PIECE_TYPES.TROJAN_HORSE: Vector2i(1, 15)
	},
}

const INITIAL_PIECE_SET_SINGLE = [
	[PIECE_TYPES.MITOSIS_PAWN, 0, 0],
	[PIECE_TYPES.KING, 1, 0],
	[PIECE_TYPES.HORSE_ARCHER, 2, 0],
	[PIECE_TYPES.STUN_KNIGHT, 3, 0],
	[PIECE_TYPES.TROJAN_HORSE, 4, 0],
	[PIECE_TYPES.EXPLODING_BISHOP, 5, 0]
]
