extends Node

enum PLAYER { ONE, TWO }
enum PLAYER_2_TYPE {
	HUMAN, AI
}

enum COLORS {
	BLACK, WHITE
}

enum PIECE_TYPES {
	ROOK,
	KNIGHT,
	BISHOP,
	QUEEN,
	KING,
	PAWN,
	HORSE_ARCHER,
	ARCHBISHOP,
	MITOSIS_PAWN,
	JOUST_BISHOP,
	ARCOBISHOP
}

const SPRITE_MAPPING = {
	COLORS.BLACK : {
		PIECE_TYPES.ROOK: Vector2i(0, 4),
		PIECE_TYPES.KNIGHT: Vector2i(0, 3),
		PIECE_TYPES.BISHOP: Vector2i(0, 2),
		PIECE_TYPES.QUEEN: Vector2i(0, 1),
		PIECE_TYPES.KING: Vector2i(0, 0),
		PIECE_TYPES.PAWN: Vector2i(0, 5),
		PIECE_TYPES.HORSE_ARCHER: Vector2i(0, 3),
		PIECE_TYPES.ARCHBISHOP: Vector2i(0, 2),
		PIECE_TYPES.MITOSIS_PAWN: Vector2i(0, 5),
		PIECE_TYPES.JOUST_BISHOP: Vector2i(0, 2),
		PIECE_TYPES.ARCOBISHOP: Vector2i(0, 2)
	},
	COLORS.WHITE:{
		PIECE_TYPES.ROOK: Vector2i(1, 4),
		PIECE_TYPES.KNIGHT: Vector2i(1, 3),
		PIECE_TYPES.BISHOP: Vector2i(1, 2),
		PIECE_TYPES.QUEEN: Vector2i(1, 1),
		PIECE_TYPES.KING: Vector2i(1, 0),
		PIECE_TYPES.PAWN: Vector2i(1, 5),
		PIECE_TYPES.HORSE_ARCHER: Vector2i(1, 3),
		PIECE_TYPES.ARCHBISHOP: Vector2i(1, 2),
		PIECE_TYPES.MITOSIS_PAWN: Vector2i(1, 5),
		PIECE_TYPES.JOUST_BISHOP: Vector2i(1, 2),
		PIECE_TYPES.ARCOBISHOP: Vector2i(1, 2)
	},
}

const INITIAL_PIECE_SET_SINGLE = [
	#[PIECE_TYPES.ARCHBISHOP, 0, 0],
	#[PIECE_TYPES.HORSE_ARCHER, 1, 0],
	#[PIECE_TYPES.MITOSIS_PAWN, 2, 0],
	#[PIECE_TYPES.QUEEN, 3, 0],
	#[PIECE_TYPES.KING, 4, 0],
	#[PIECE_TYPES.BISHOP, 5, 0]
]
